# Generated by Django 2.2.2 on 2019-07-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190628_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read_or_not',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_or_not', models.BooleanField()),
                ('due_date', models.DateField(blank=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
        ),
    ]
