# Generated by Django 2.2.2 on 2019-07-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_read_or_not'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_or_not',
            new_name='Already_read',
        ),
    ]
