# Generated by Django 2.2.2 on 2019-08-01 06:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190702_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='profile/', verbose_name='저자 프로필 사진'),
        ),
    ]
